//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScsDispatcher.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScsDispatcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Data/distance.data ähnelt.
        /// </summary>
        internal static string DinstanceDB {
            get {
                return ResourceManager.GetString("DinstanceDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ATS/ats_cargo_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCargosATS {
            get {
                return ResourceManager.GetString("LanguageCargosATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ETS/ets_cargo_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCargosETS {
            get {
                return ResourceManager.GetString("LanguageCargosETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ATS/ats_cargo_user_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCargosUserATS {
            get {
                return ResourceManager.GetString("LanguageCargosUserATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ETS/ets_cargo_user_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCargosUserETS {
            get {
                return ResourceManager.GetString("LanguageCargosUserETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ATS/ats_cities_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCitiesATS {
            get {
                return ResourceManager.GetString("LanguageCitiesATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ETS/ets_cities_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCitiesETS {
            get {
                return ResourceManager.GetString("LanguageCitiesETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ATS/ats_companies_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCompaniesATS {
            get {
                return ResourceManager.GetString("LanguageCompaniesATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ETS/ets_companies_de.lang ähnelt.
        /// </summary>
        internal static string LanguageCompaniesETS {
            get {
                return ResourceManager.GetString("LanguageCompaniesETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ETS/ets_countries.list ähnelt.
        /// </summary>
        internal static string LanguageCountriesETS {
            get {
                return ResourceManager.GetString("LanguageCountriesETS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Language/ATS/ats_states.list ähnelt.
        /// </summary>
        internal static string LanguageStatesATS {
            get {
                return ResourceManager.GetString("LanguageStatesATS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Graphics/MapPics ähnelt.
        /// </summary>
        internal static string MapFolder {
            get {
                return ResourceManager.GetString("MapFolder", resourceCulture);
            }
        }
    }
}
